# This is a configuration file for GitHub Pages.
# You can set a custom theme!
# Read https://pages.github.com/themes/ for all themes that you can use!

remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

# Use remote-theme:  for themes outside of GitHub's themes.
